### ISSUE TITLE
Replay Subject for edge cases

### ISSUE THREAD

**Issue by rupamroy** [DanWahlin/Observable-Store#106]
This is more of a feature enhancement request wherein in the configuration object we should be able to request a replaySubject instead of the default behavior Subject.

This is mostly required for edge cases , but so is why replaySubject was designed. 

**Scenario :** I have a search form and based on the result I want to display a two different components . Those components do subscribe to the store to get the data in state. Now these two components are not present in the DOM initially, so they do not form the subscription. However when the main component gets the results one of them gets rendered (by virtue of an *ngIf condition) and thus subscribe to the state, but by then the behaviour subject is complete and hence even if they subscribe they won't get the last fetched data. 

This case can be solved if the the subject is a replaySubject where even thought the subject is completed , when freshly subscribed it would get the last fetched data.

**Comment by DanWahlin** [comment]
Thanks for the suggestion!

With BehaviorSubject late subscribers such as in your scenario will still get the last state sent out. However, they won't get any of the state before that last state value of course since BehaviorSubject is really a ReplaySubject(1). Are you looking for the component to get everything that went into the store over time (replay all state changes) or just the latest change? Currently the store will send the latest state so I wanted to check on that part of your scenario there.

**Comment by rupamroy** [comment]
I will prepare a stackblitz so that I can explain what is wrong.

**Comment by DanWahlin** [comment]
Sounds good. Thanks.

**Comment by rupamroy** [comment]
I think I was wrong, the issue was the component subscribing to the store was not running the subscription code until it was getting initialized inside ngInit , once I changed the subscription to the constructor things worked fine. 

Closing this issue.
