### ISSUE TITLE
Missing properties after setting state

### ISSUE THREAD

**Issue by Andrewthedev** [DanWahlin/Observable-Store#108]
Thank you for this wonderful package.

I am having issues using it in an Angular 10 application using Typescript.

I have setup a store almost identical to the ones provided in the sample application. I have an interface that looks like this: 

```
export interface FileStoreState {
  files: ImportedFile[];
  selectedFiles: SelectionModel<ImportedFile>;
}
```

I then create a service that extends `ObservableStore` and give it a type of `FileStoreState`

```
@Injectable({
  providedIn: 'root'
})
export class FileService extends ObservableStore<FileStoreState> {
  
  constructor() {
    super({ trackStateHistory: true, logStateChanges: true });
   
    const initialState = {
      files: [],
      selectedFiles: null
    }
    this.setState(initialState, FileStoreActions.Init)
  }

  addFiles(files: Array<ImportedFile>) {
    let state = this.getState();

    files.filter(x => {state.files.push(x)});

    this.setState({ files: state.files}, FileStoreActions.AddFiles)
  }

}

```

Now my imported File looks like this: 

```
export class ImportedFile {
    electronFileId: string;
    type: string;
    size: string;
    path: string;
    bytes: any;
}
```
I call the `addFiles` function in on of my components.

```
  filesSelected(files: File[]) {    
    let mappedFiles = files
      .filter(x => this.isAcceptedFileType(x))
      .map(x => new ImportedFile(x, FileType.fileSystem));

    **this.fileService.addFiles(mappedFiles);**
  }
```

When I console log `mappedFiles` it gives me a result that looks like this:

![image](https://user-images.githubusercontent.com/10337752/108763594-87efae80-751f-11eb-91e8-a537c283511e.png)

Which is perfect! It has all of the properties and data I am expecting..

When `addFiles` is called in the service it should push those files into the `files` state within the store.

This is where it gets weird... In the console log of the STATE CHANGED it looks as if the files are there with their associated data.

![image](https://user-images.githubusercontent.com/10337752/108763896-eae14580-751f-11eb-9875-879b23f8fb10.png)

Yet, when I subscribe to state changes the `bytes` property disappears completely when I subscribe. Also, checking the state afterward shows that the property is no longer there. This is happening with multiple typescript interfaces I am trying to use.

```
this.storeSub = this.fileService.stateChanged.subscribe(state => {
      if (state) {
        if (state.files.length > 0) {
          console.log(state.files);
          this.files.data = state.files;
        }
      }
    });
```

The console log now displays this: 

![image](https://user-images.githubusercontent.com/10337752/108764281-64793380-7520-11eb-92b9-8aca66f0d0a5.png)

Which are the files that I was expecting yet, its missing the `bytes` property. Also, now when I try and do a `this.getState()` its also missing from there even though the state change log says it should be there.

None of this makes sense, I'm unsure why this is happening. This is a simple example, it seems to be happening on every single object I am trying to save the state of. For example: SelectionModel ends up losing its functions like `toggle` and `select`

Thank you!

**Comment by DanWahlin** [comment]
Hi Andrew. Thanks for providing the details. As far as toggle and select that you mention, functions can't be stored. The store only supports JSON objects and functions aren't something JSON supports.

As for the missing bytes property, can you show the code that calls setState() to add the files array into the store? It looks like that must happen in addFiles() but without that code it's hard to see if something is going on there.

Also, due to the specific scenario, if you're able to put together a simple https://stackblitz.io project that duplicates the overall issue that would be great. It's much easier to help if I'm able to run the code and duplicate the issue.

**Comment by Andrewthedev** [comment]
Mr. Wahlin

Wow, I truly appreciate the quick response! 

Thank you for clearing up the `toggle()` and `select()` as that makes a lot of sense! It appears I was trying to do a little too much with storing the functions. I always try and do too much so that is on me!

I do see the properties right before I try and call setState through the console.log. The properties also do appear in the state change history. Although they show up in the history change log, retrieving them from the state after that point somehow erases them.

This is the `console.log(state.files)` 

![image](https://user-images.githubusercontent.com/10337752/108768456-a9ec2f80-7525-11eb-86c7-85cafa4a0411.png)

So it looks good there, but when I get the state afterward they seem to not be cloned for some reason.  

I will try and get up a stackblitz fairly soon and thank you tremendously for the help!

**Comment by DanWahlin** [comment]
One more thing to try, if you do this:

```
this.setState({ files: state.files}, FileStoreActions.AddFiles);
console.log(this.getState().files);
```

I'm assuming the log won't show the bytes in the files array? Wanted to double-check right at that spot rather than in a subscription.

I'm assuming you don't see bytes in there right?

**Comment by Andrewthedev** [comment]
Correct! How are you doing this magic, are you inside of my computer?! haha

**Comment by DanWahlin** [comment]
Hah - OK thanks. That definitely narrows it down to the setState() mechanism and I'm guessing the cloning library that is used internally. We use this in a really robust project and haven't seen properties drop out like this but if you get time to make a mini-demo that would be great (Stackblitz, Github repo, or even a .zip that I download and run locally). Thanks.

**Comment by Andrewthedev** [comment]
I think the issue is that I am trying to save a byte array as a string and its just way too large. Those two properties are the only ones that are not cloning properly. There must be a size limit. I think I am just misusing the library with such large data.

**Comment by DanWahlin** [comment]
Interesting - that could be the problem. For some reason I didn't realize that the `bytes` property represented the file contents (makes sense now that I think about it). Are we talking massive amounts of data in some cases? If so I'd definitely think through if you want that much data stored since it'd of course impact memory.

The cloning functionality happens here:

https://github.com/DanWahlin/Observable-Store/blob/main/modules/observable-store/utilities/cloner.service.ts

I'm wondering as a quick test if you can put some fake data in for the "problem properties" (bytes, etc.) and see if that works. If it does then I suspect a size limit may be the problem as you suspect. I'm not sure why they would just drop out though entirely - would have to research that more.

**Comment by DanWahlin** [comment]
If you are able to send me one of those JSON objects with the full bytes in it I'll try to make some time to test to see if JS is just not accepting it, the cloning library is causing it, etc. It'd be nice to at least throw an error if that scenario comes up so that there are no surprises in that case.
