### ISSUE TITLE
Store structure: Flat vs Complex + stateWithPropertyChanges returns function if that's what was passed in the setState

### ISSUE THREAD

**Issue by orosro** [DanWahlin/Observable-Store#126]
Hello @DanWahlin,

Thanks for the library,  I'm using in in building a micro frontend platform with influence from Observer pattern. 
I wanted to encapsulate the properties that are stored by the services so I though of having a more complex structure for the store:
```
export interface StoreState {
	[key: string]: any;
	 'pro-registry': ProRegistryStore;
	 'pro-auth': ProAuthStore;
	// 'pro-filters': any;
	// 'pro-settings': any;
}

export interface ProRegistryStore {
	publicApps: ApplicationConfig[];
	privilegedApps: ApplicationConfig[];
}

export interface ProAuthStore {
	isAuthenticated: boolean;
	currentUser?: any; // TODO: set correct interface of User imported from generated OpenApi
}

```

Now, with this structure I saw several issues:
1. Weird redux dev extension chart, I opened a separate ticket for this
2. When I want to setState, I can't update just the property I want, I need to update the entire section of the store, which leads me to the next issue:
3. When using stateWithPropertyChanges, because I've sent the entire service "store section", I'm going to get back exactly what I sent, not  just the difference in the state. Now, If I send only the property I want, I'm gonna get only that one but the store is completely changed
4. When using a function to setState, the return value of stateWithPropertyChanges is the state and the function that I used in the stateChanges argument. I expected to have an object instead of the function.

More details

 Setting a deep property

This is how I do it
```	
private updateStateCurrentUser(user, dispatchState: boolean = true): void {
		const authState = this.getState();
		const newState = {
			[ProAuthStoreName]: { ...authState, ...{ currentUser: user } },
		};

		this.setState(newState, ProAuthStoreActions.SET_CURRENT_USER, dispatchState);
	}
```
And it works, but unfortunately, it sees it as an update of the entire ProAuthStoreName property, when I only change currentUser. This issue flows down to the stateWithPropertyChanges method, which returns the entire object instead of property that was changed.

Now, This would not be a problem, but when using stateWithPropertyChanges, I can't make use of the  stateChanges parameter because it's the same with the actual state, I would like to compare it with the old values, similar to how redux works.

Do you think that would be a good idea, to return  something like
```
interface StateChanges {
    oldState: any;
    newState: any;
}
```

**Comment by DanWahlin** [comment]
Thanks for the info @orosro. In order to keep Observable Store as simple as possible it will only notify changes on top-level properties as you've discovered. Changing the StateChanges interface is challenging due to backward compatibility for others using it. However, in a future version it would be possible to consider adding what you're proposing. I can see how that would be useful in this case. 

I don't have any plans to change that specific behavior right now but if you have any interest in creating a PR for the functionality you'd like to see there I'd be happy to look at what you propose more. I can't make any promises without seeing more details, but I'm always open to new functionality as long as it preserves the simplicity of the library.
