### ISSUE TITLE
This lib can be performance problems

### ISSUE THREAD

**Issue by wechirp** [DanWahlin/Observable-Store#170]
this.getState  is deep clone ,  often call  ,  very slow   ,  must optimizing this

**Comment by DanWahlin** [comment]
That would only be true if you have massive amounts of data being stored in the store. However, that would be a bad use case for this library or any front-end library IMO. With real life usage performance hasn't been an issue since most devs aren't storing massive amounts of data in the store. There is an option to opt out of deep cloning when very large amounts of data do need to be stored (that has tradeoffs though).

If you have an optimization please submit a pull request. We don't have any plans to change this behavior right now.
