### ISSUE TITLE
Using JSONPath and Observable store

### ISSUE THREAD

**Issue by arash-sahami** [DanWahlin/Observable-Store#178]
Hello Dan,
I'm very interested to hear you opinion about the following additional feature to the Observable-Store.
In my case I need to listen to property changes of object which might be nested or perhaps a property of an object in an array.
Therefor I experimented by adding the following method to the Observable store:
```
  onPropertyChange<T>(jsonPath: string): Observable<T | undefined> {
    return this.stateChanged.pipe(
      map(state => {
        if (state != null) {
          // The return value of JSON Path is array.
          //See for more information https://stackoverflow.com/questions/23608050/getting-a-single-value-from-a-json-object-using-jsonpath
          const values = JSONPath({ path: jsonPath, json: state as any});
          return values[0];
        }
        return undefined;
      }),
      distinctUntilChanged(),
      skip(1)
    )
  }
```
In the method above I use the npm package `jsonpath-plus`. 
And we can then run the following test to subscribe to changes of a property of an item in an array:
```
    it('should receive notification upon array item property change', waitForAsync(() => {
      const updatedCity = 'Los Angeles';
      let mockStore = new MockStore({});
      const user = { name: 'U1', address: { city: 'Boston', state: 'Mass', zip: 888 } } as MockUser
      mockStore.UpdateUsers( [user]);
      const sub = mockStore.onPropertyChange<string>(`users[?(@.name=="${user.name}")].address.city`).subscribe((city: string | undefined) => {
        expect(city).toBe(updatedCity);
      })
      if (user?.address != null) {
        user.address.city = updatedCity;
        mockStore.UpdateUsers([user]);
      }

      sub.unsubscribe();
    }));
```
Any thoughts?
Thank you in advance
Arash

**Comment by DanWahlin** [comment]
Hi @arash-sahami! I really like that idea - thanks for sharing. I don't know if I'd add it to the Observable Store core since it would add a library (jsonpath-plus) that not everyone would need, but I'm wondering if it could be an extension/add-on?

Right now there is only 1 extension (React Redux tools) so there may be more work that would have to be done to integrate something like this, but I think it would be a great extension/add-on and happy to talk about it more. If you get a chance, let me know your thoughts on that. 

Currently extensions are added using this code in the base class:

https://github.com/DanWahlin/Observable-Store/blob/main/modules/observable-store/observable-store-base.ts#L71

Here's an example of where init() is called in the Redux DevTools extension. For your idea, init() would need to be able to add the onPropertyChange() functionality into the overall store so more "context" would probably have to be passed to init() to add that function to the prototype or something like that.

https://github.com/DanWahlin/Observable-Store/blob/main/modules/observable-store-extensions/redux-devtools.extension.ts

Here's an example of adding the extension in a sample:

https://github.com/DanWahlin/Observable-Store/blob/main/samples/angular-simple-store/src/main.ts#L22

It'd be great to be able to leverage something like this to allow people to add-in what you mention above. I had someone else that wanted localStorage support to be added which I don't want to add to the "core", but that could also be a great extension.

**Comment by arash-sahami** [comment]
Hi,
Thank you for your quick response. I'm glad you like the idea.
I fully understand that you want to keep the core functionality clean and efficient. 
Of course one can also inherit from `ObservableStore` and add this functionality or any additional functionality to it.
However I like your idea about adding different features as extension. I already use your redux devtool extension and it is very helpful. 
Also the idea of being able to store the storage in local or session storage is also very interesting for the use cases where one wants to keep the data to remain event after page reloads. 

Thank you for sharing this project. If I find some free time I will try to investigate how this feature could be added as extension to the existing observalbe store.

**Comment by DanWahlin** [comment]
I think your idea would definitely be a great example for an extension that could then be "extended" to other ideas like localStorage, etc. That way people can use only the core or use the core + as many extensions as they'd like. 

If you get a chance to look at what I have there currently let me know your thoughts (some additional context would likely have to be passed to init() in the extension I suspect).

**Comment by DanWahlin** [comment]
@arash-sahami: I'm going to close this since I think we both agree this would be a good extension opportunity. If you end up getting time to look into that more please let me know. Happy to work with you it and modify the extension API as needed to make something like this work. Really appreciate you sharing the idea - I like it!
