### ISSUE TITLE
CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by ericcoulthard** [DanWahlin/Observable-Store#221]
Thanks for such a cool library.

Ever since upgrading to Angular 12 and then 13, I have been getting this warning from this package.

Warning: path_to_my_service/my-service.ts depends on '@codewithdan/observable-store'. CommonJS or AMD dependencies can cause optimization bailouts.        
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

Is there a plan to remove the dependency on common.js?

**Comment by DanWahlin** [comment]
Due to the number of ways this can be used outside of Angular and the small overall size of the library I don't have plans to change that right now. The warning can be removed using angular.json if you need it to stop displaying though. In the future I'll reevaluate that, but there are specific testing scenarios outside of Angular where people are using it that still require CommonJS.

**Comment by ericcoulthard** [comment]
Thanks very much for such a prompt reply.

**Comment by DanWahlin** [comment]
No problem. :-) I'd like to change that at some point (especially since I personally only use it with Angular) but don't want to break other folks. I'll consider it again in the next major version. It's so small that the bailout doesn't have much affect. It's annoying to have to suppress the warning I know, but fortunately angular.json makes it pretty easy.
