### ISSUE TITLE
not working out of the box with jest

### ISSUE THREAD

**Issue by roger-gl** [DanWahlin/Observable-Store#38]
I get the following error when I run a test that uses the store with jest:

 SyntaxError: Unexpected token export

      1 | import {Injectable, OnDestroy} from '@angular/core';
    > 2 | import {ObservableStore} from '@codewithdan/observable-store';

I tried to add transformIgnorePatterns like:

 "transformIgnorePatterns": [
      "node_modules/(?!@@codewithdan|observable-store)"
   ]

But it did not help.

**Comment by DanWahlin** [comment]
Thanks for the information. I don't use Jest so I'd need to see a project that has all of the required pieces in place. If you're able to create and share a simple project I'll be happy to take a look.

**Comment by roger-gl** [comment]
The easiest thing would be to just create a simple project with nx. I'll try to do that on Sunday.

**Comment by DanWahlin** [comment]
Sounds good. I'm out on vacation this next week but I'll look at it once I get a chance.

**Comment by rogergl** [comment]
Thanks. You can find the project here: https://github.com/rogergl/os-test

**Comment by DanWahlin** [comment]
Thanks for the project. I looked into this and it's due to how Jest handles ES2015 modules (or rather doesn't handle them) from what I can tell. Observable Store compiles using ES2015 for the module setting since it's designed for apps using ES2015 modules. However, Jest has some challenges with that from what I've seen in the various repository issues. Here's a specific post related to ts-jest:

https://github.com/kulshekhar/ts-jest/issues/970

It implies that the transformIgnorePatterns you tried should work but I couldn't get that to work either. It may be a matter of updating the value to something different potentially but I'm not sure having never used Jest or that setting before.

I tried compiling Observable Store using `commonjs` instead of `es2015` in my tsconfig and that does work with Jest and your project, but I'd have to research implications of making that type of change before actually implementing and releasing a new version with it. 

It's not something I'm going to have time to look into right away since this isn't technically an Observable Store problem and more of a problem with how Jest handles ES2015 modules. If I end up changing the module setting and releasing a new version with that I'll let you know.

**Comment by roger-gl** [comment]
Ok, thanks for the help. Right now I added the sources of this project just as a lib and with that change Jest works.

**Comment by DanWahlin** [comment]
Glad that works for the short-term. I'm hoping to look at switching it to commonjs once I get back from a trip I have this month. Just need more than 24 hours in a day. :-)

**Comment by DanWahlin** [comment]
As an update, version 2 of the project is going to use CommomJS so it should work out of the box with Jest. I’m hoping to release it soon.

**Comment by roger-gl** [comment]
Great news. Thanks

**Comment by DanWahlin** [comment]
v2 is now out and it uses CommonJS. Give it a try when you get a chance.
