### ISSUE TITLE
Why stateChanged: Observable<any>?

### ISSUE THREAD

**Issue by GustavoCostaW** [DanWahlin/Observable-Store#39]
https://github.com/DanWahlin/Observable-Store/blob/af91393730f15b68123ff0192a9735a6c4fcc6da/src/observable-store.ts#L38

why

```
stateChanged: Observable<any>?
```
instead of:
```
stateChanged: Observable<T>?
```

Why the generic type passed is not used in the state changes observable type return?

In this case above, I can't take advantages as vscode autocomplete, I needed to create another observable called `stageChanges` specifying the Observable returned type to have this feature:

<img width="599" alt="Screen Shot 2019-09-04 at 19 29 31" src="https://user-images.githubusercontent.com/874909/64297755-c750c680-cf4a-11e9-88ba-1cedaa30c1af.png">

subscribing into `stageChanges` instead `stageChanged`, and then I have the autocomplete, 

<img width="601" alt="Screen Shot 2019-09-04 at 19 37 25" src="https://user-images.githubusercontent.com/874909/64298298-74c3da00-cf4b-11e9-831a-d46531df0c74.png">

I was thinking about to send a PR but maybe there is a reason for it.

Are there any reasons why there is no generics usage?

**Comment by DanWahlin** [comment]
Users can define a stateSliceSelector() function which can return a slice of state from the store when the state changes. Since there's no way to know what they'll pass back if that function is defined (it's optional, but has to be considered for this scenario), using T wasn't an option.

I normally define the type when subscribing which removes the need for what you mention above. 

I'm open to ideas though if you come up with a way to handle that while preserving the functionality of the stateSliceSelector() option.

**Comment by DanWahlin** [comment]
As an update, version 2 is going to go with stateChanged: Observable<T>. People using the slice functionality can cast to their own type when subscribing. Thanks for the suggestion. I’m hoping to release v2 soon.

**Comment by DanWahlin** [comment]
v2 of Observable Store is out and it changes the stateChanged type as mentioned above. Give it a try when you get time.
