### ISSUE TITLE
stateSliceSelector function example

### ISSUE THREAD

**Issue by tobang** [DanWahlin/Observable-Store#4]
Could you add an example on how to use a stateSliceSelector function to the docs.

Thank you

**Comment by DanWahlin** [comment]
I like the suggestion - thanks. That was a great contribution by @mickeypuri so let me see if he has anything he can share here. I'll also look at getting something in the docs on that eventually.

In a nutshell though, you'll be passed the state to the stateSliceSelector function that you define and then it'd be up to you to decide what gets returned. Doing that allows for control over what components see as the globalStateChanged event fires. 

Here's some psuedo-code (off the top of my head :-)):

```typescript
this.storeSub = this.customersService.globalStateChanged.subscribe(state => {
        this.customers = state.customers;
});
```

In this case you'd get all of the store state since globalStateChanged was used. But, if in the store you supply a stateSliceSelector you can filter that down. For example, if CustomersService has access to quite a bit in the store but you only want a "slice" of that date you can filter it down and only return the specific data you need state subscribers to that service to get:

``` typescript
export class CustomersService extends ObservableStore<StoreState> {
  constructor() { 
    super({ stateSliceSelector: (state) => state.selectedCustomer });
 }
}
```

But, I'll see if we can formalize this a bit more in the docs in the near future. Thanks for mentioning it.

**Comment by tobang** [comment]
Thank you for a very detailed answer. I will try that.

**Comment by DanWahlin** [comment]
Added this into the readme
