### ISSUE TITLE
The state always contains the complete state of all stores ?

### ISSUE THREAD

**Issue by roger-gl** [DanWahlin/Observable-Store#44]
e.g.:

```
  this.subs.sink = this.auctionsStoreService.stateChanged.subscribe(
         (state: AuctionState) => {
```

state contains all data from all other stores und not just the data that is related to auctions ? is that the expected behavior ?

**Comment by DanWahlin** [comment]
There’s only one store no matter how many services you create (which is by design and very important to avoid state being scattered all over - otherwise you could just use a service to store it’s own state). But, stateChanged will only fire when a given service calls setState(). So in your case, when auctionsStoreService calls setState() then auctionStoreService.statechanged will fire and you can grab whatever state you need.

**Comment by roger-gl** [comment]
Thanks for the fast reply. Ok if that is the design it's like it is, but please allow me one more question since I just run into this issue. I forgot to assign a state property in one store, but had this property in the interface for that store. The same property was set by another store leading to the fact, that the app used the wrong data. I know it was my fault, but I'm afraid that this error can happen to easely. Any ideas or best practices on how to avoid such mistake ?
-

**Comment by DanWahlin** [comment]
Let me clarify a few terms first so we’re talking about the same types of objects. Observable Store has the following characteristics:

1. Provides a single store and a single interface for that store’s state.
2. You can have many services that interact with the store. When done properly each service will follow the single responsible rule (see the image at the top of the repository’s readme to visualize this).

It’s goal is to provide a simple way to get data in and out of the store and be notified when the store state changes.

For your scenario, I don’t know that there’s a particular best practice that would help since it sounds like an error was made in the coding. If your services follow the single responsibility rule that should help though. A CustomersService would only work with customers data in the store, OrdersService would only work with orders data in the store, etc.

When subscribing to store state changes you’d also always want to check for nulls in the returned state since a given store value may or may not be available at that time.

Hope that helps some.

**Comment by roger-gl** [comment]
Thanks again for the answer. I now started to give the store more structure by having a property for each service (customer, orders and so on). Which that approach I feel much more comfortable. The only problem so far is, that stateWithPropertyChanges does not work for nested properties.

**Comment by DanWahlin** [comment]
Good deal. That’s typically how I organize the store structure as well. 

As far as stateWithPropertyChanges, it fires when setState() is called by the given service (assuming there’s a subscriber) and passes the state that was set as the second parameter. Since you can’t set a nested property directly (due to having to go through the parent property), it won’t be able to pass a nested property that changed when stateWithPropertyChanges fires since there could be several properties that could change all at once. 

For example, customer.firstName and customer.lastName could be set together. The customer value would therefore be passed to the subscriber of stateWithPropertyChanges.   If you need to compare nested properties then you’d need to compare before and after values wherever you subscribe to stateWithPropertyChanges.
