### ISSUE TITLE
setState very slow

### ISSUE THREAD

**Issue by wa1gon** [DanWahlin/Observable-Store#45]
```
    public addShowInfo(showInfo: ShowInfo) {
        console.log("start set showinfo state")
        this.setState({ showInfo: showInfo }, ShowInfoStoreActions.AddShowInfo);
        console.log("finish set showinfo state")
    }
```

I have this simple setState which takes about 3-4 seconds to run.  Any idea why?

**Comment by wa1gon** [comment]
After doing some experimenting I found that the reason for the slowness is that I have a very large store (9000 records of contacts).  So I guess I will have to do different stores for each large data set unless you have a better option.

**Comment by DanWahlin** [comment]
Since store state is immutable, data is cloned during a call to setState(). If you have a ton of data then I suspect that is causing the slowdown since each record would be cloned and it sounds like you’re adding a lot of data all at once. I don’t have a way to avoid that since the data needs to be immutable (aside from not putting everything into the store all at once).

It would be possible to add a feature to turn off cloning during setState() but I’d have to think through the other problems that would introduce. My first thought is that if setState() is being slow due to the immutable nature of the store that another approach for the data might need to be considered.

**Comment by wa1gon** [comment]
I agree, I am using CouchDb as a DB and as a result some of the documents are fairly large.  I guess there are going to be many things I have to rethink to use the store pattern. ;-)
I think your library is really great and I think I would have the same issue with ngRx because it will have to do a deep clone.  Also, think you for getting back so quick.

**Comment by DanWahlin** [comment]
I can see how that would present a challenge with large and deeply nested data. As a heads-up, when you set ObservableStore.globalSettings.isProduction to true then only a shallow copy is made (in Dev a deep copy is always made which is slower of course) so it should be faster in that mode.

I’m going to give more thought to adding a parameter to setState() that would disable cloning in this type of scenario. That introduces other challenges since the data would be mutable, but by setting that a dev would be explicitly taking over control and be responsible for not mutating the data. I’ll think it over more.

**Comment by wa1gon** [comment]
Oh, what a different setting isProduction to true makes.  Thank you.

**Comment by DanWahlin** [comment]
Awesome! Good to hear. Heard about that trick (deep cloning in dev to prevent mutations and shallow cloning in prod) from one of the NgRx guys.

**Comment by DanWahlin** [comment]
As a heads-up, due to some edge cases that came up I ended up having to do deep cloning when setting and getting state even in production. So, if you're still using it to store large amounts of data you may see an impact with v2.2.8. However, setState() and getState() now have a deepClone boolean property that can be passed (https://github.com/danwahlin/observable-store#store-api). So, when adding all of the records you mentioned above you could do something like the following potentially:

`this.setState(yourState, 'Your Action', true, **false**);`
`this.getState(false)`

The last `false` value would tell it to NOT do a deep clone on the state being added. That's good for performance, but any changes to the data outside of the store could affect the store data since it'd be stored by reference without any cloning in that case.
