### ISSUE TITLE
Store state get's overwritten when using ReduxDevToolsExtension

### ISSUE THREAD

**Issue by riscie** [DanWahlin/Observable-Store#47]
Hi there

Great project, first of all. I really enjoy the simplicity!
I've played around with it a little bit and introduced a simple scenario in one of our angular apps. It all works quite well until I add the following line to my **main.ts**

```
ObservableStore.addExtension(new ReduxDevToolsExtension());
```
Now what I observe is, that the state of my store get's overwritten by what seems are routing events:

```
{
  "__devTools": {
    "router": {
      "path": "/admin"
    },
    "action": "ROUTE_NAVIGATION"
  }
}
```

Here is my store:

```
import {Injectable} from '@angular/core';
import {ObservableStore} from '@codewithdan/observable-store';
import {SettingsStoreState, TenantSettings} from './settings.store.state';
import {Observable, of} from 'rxjs';
import {TenantSettingsDataApiService} from '../services/tenant-settings-data-api.service';
import {tap} from 'rxjs/operators';

@Injectable({
    providedIn: 'root'
})
export class SettingsStore extends ObservableStore<SettingsStoreState> {

    constructor(private tenantSettingsDataApiService: TenantSettingsDataApiService) {
        super({trackStateHistory: true});
    }

    get() {
        const settings = this.getState();
        if (settings) {
            return of(settings);
        } else {
            return this.tenantSettingsDataApiService
                .getSettings()
                .pipe(
                    tap(res => this.setState(res))
                );
        }
    }

    update(settings: TenantSettings): Observable<any> {
        return this.tenantSettingsDataApiService.updateSettings(settings)
            .pipe(
                tap(() => this.setState(settings, 'UPDATE_SETTINGS'))
            );
    }
}
```
So the first call to `this.getState()` somehow returns the Routing-Event which I posted above. (When it actually should find an empty state and initialize the store with the data from the backend).
How is this possible?

Thanks for any pointers to a solution.

Kindly, riscie

**Edit**
So I found the code, which adds the `ROUTE_NAVIGATION` Action. It's part of the redux extension here: https://github.com/DanWahlin/Observable-Store/blob/master/modules/observable-store-extensions/redux-devtools.extension.ts.
I am just no sure yet, why this is getting written into my own store.

**Comment by DanWahlin** [comment]
Thanks for checking out the new dev tools extension and the overall project. Appreciate it!

The property you’re asking about is added automatically during debugging with the redux dev tools in order to associate routes with the data for each route. Otherwise the redux dev tools wouldn’t know what to navigate to when history is replayed. 

It’s only there when the dev tools are enabled and can be quite useful for tracking down exactly when things are happening (route changes as well as your state changes). The property is prepended with __ to infer its private but your data will still be there as well. It basically sits in the background and if you replay history will be read by the dev tools to trigger the necessary route navigation. It sounds like I need to mention that in the docs as well though which is probably a good idea. 

I’ve considered storing that information externally but for the first release of the extension decided the additional complexity wasn’t worth it. But, I’ll continue thinking through that more for future releases. 

Let me know your thoughts on that. Would adding some info into the docs be enough or would you want the properties for routing stored privately outside of the store knowing that it wouldn’t be as easy to associate an action with a route just by looking at the raw store data?

**Comment by riscie** [comment]
Hey Dan!
Thanks for getting back at this so fast, really appreciated!

It makes a lot of sense now and I really see the benefit of having the routing information alongside the store data. 
The thing I dislike with the approach is, that it breaks code, which is valid without the devtools. Like the one I have above:

```
if (storedata) {
    return of(storedata);
}
else {
    // ...
}
```

If I see it correctly, I would have to rewrite the predicate `if (storedata)` so that it ignores the 'private' object property `__devTools`, right? This is a bit unexpected.

So if you ask me, I would seperate the extensions metadata from the storedata. If we could get a seperate place, where the extension metadata is stored, maybe we could have the store's data there as well, so that we still have the benefit of associating an action with the route?

For a start, I think having it mentioned in the docs is a good step.

**Comment by DanWahlin** [comment]
That’s a great point if you’re simply wanting to know if the store exists or not. I alway initialize mine with empty properties to start things (and then check if a given store property has a value or not) but in scenarios where you don’t want to do that the private property would definitely mess that up.

In the short term I’ll get the docs updated but in the long-term I’ll start thinking through what I’d need to do to make the private info completely separate. The tool assigns an ID so it’s definitely possible (I think 🤔), just some work to make it happen. Thanks again for the feedback.

**Comment by riscie** [comment]
Thanks again! I will handle it, the way you suggest it. Maybe I can provide more insights afer having worked a bit more with the library and the devtools.

**Comment by DanWahlin** [comment]
Sounds great...thanks!

**Comment by DanWahlin** [comment]
I added a section about the `__devTools` property into the readme so I'm going to close the issue. However,  I've added your suggestion to my list of future enhancements and will definitely be thinking that through more. Thanks again for asking about it!
