### ISSUE TITLE
Parameter stateChanges: Partial<T> of dispatchState method

### ISSUE THREAD

**Issue by clgraf** [DanWahlin/Observable-Store#49]
Hi there, dispatchState method has the signature 
`protected dispatchState(stateChanges: Partial<T>, dispatchGlobalState: boolean = true)`
What the purpose of stateChanges parameter, if the ideia is to dispatch the current state of the store and the doc says 

> without modifying the store state?

**Comment by DanWahlin** [comment]
It's used internally 99% of the time and dispatches the state to any listeners on a given service that derives from ObservableStore and also dispatches the state to any global listeners that want to know about all state changes. Nothing in the store is modified though with this call, the state is only dispatched/sent out to listeners. That's different than calling `setState()` (which will normally be used) because it modifies the store state and then dispatches the state via a call to `dispatchState()`. Here's what `dispatchState()` looks like:

https://github.com/DanWahlin/Observable-Store/blob/master/modules/observable-store/observable-store.ts#L197

In cases where you don't want the state dispatched to go out to global listeners (you only want a given service's listeners to get the state) you can pass the state and `false` for the second parameter to it to prevent the global listeners from being notified.
