### ISSUE TITLE
Testing capabilities

### ISSUE THREAD

**Issue by svehera** [DanWahlin/Observable-Store#52]
Hello, Dan was playing around with Observable-Store library in Angular application and now when I come up to the unit testing of service that implements ObservableStore<T>  I am not sure what is a proper way to test it. 
I have not found any hints in the documentation about the unit testing. 
I have tried to track state history in tests, but I would like to have a possibility to reset State in a testing environment without the need to implement it in each service I am going to unit test. 
I think there might be some other features that can be included in the 'observable-store/testing' module.

**Comment by DanWahlin** [comment]
I currently don't have any samples for that although I'd like to get some added at some point. The best thing I can recommend right now is to look at the unit tests for the library itself:

https://github.com/DanWahlin/Observable-Store/tree/master/modules/observable-store/tests

I'll add the ObservableStore.resetState() (probably be a static member) idea to my list of future considerations. Thanks for sharing. 

I'm going to close this since it's been added to my list, but if you have any additional ideas there let me know in this thread as well. Thanks.

**Comment by DanWahlin** [comment]
One more thing on this. If something like `ObservableStore.resetState(state)` was added would you want it called `resetState` or `setState`? My problem with calling it `setState` is that it might be confusing with the normal `setState` member that each service that uses ObservableStore would have access to. There's already an `ObservableStore.resetStateHistory()` API (which I use for testing the store) so I'm thinking `ObservableStore.resetState()` makes the most sense for consistency (and less confusing APIs). Let me your thoughts.

**Comment by DanWahlin** [comment]
I just realized that I should've mentioned that the latest version (which just went out a few days ago) added an ObservableStore.initializeState() static member (you'll see it in the unit tests). It has to be called before any service has been initialized since it can only be called once, but since your tests would be initializing a new service normally let me know if that would work. I'm also considering adding an ObservableStore.resetState() static member that could be used to reset the overall store state at any time.

**Comment by DanWahlin** [comment]
As an update, I just added an ObservableStore.resetState(state) static function. After thinking about it more this could be useful in a scenario where a user cancels an operation they're doing and that action requires the store to be reset to a different value. It could possibly be useful in testing as well if one or more service instances need to be kept around for multiple tests but the store state needs to be reset.

I haven't officially published the package yet, but you can see it in the docs for the repository readme now. 

https://github.com/danwahlin/observable-store#api

**Comment by svehera** [comment]
Great! Thank you for the quick reply. I'll be glad to test it out in my tests. I have some thoughts and ideas that I will share in this thread or another later.

**Comment by DanWahlin** [comment]
Sounds great! I just pushed out the update: 2.2.6
