### ISSUE TITLE
ReduxDevToolsExtension console error

### ISSUE THREAD

**Issue by trentsteel84** [DanWahlin/Observable-Store#53]
I'm getting the following console error:

```
Uncaught TypeError: this.window.getAllAngularRootElements is not a function
    at new AngularDevToolsExtension (angular-devtools-extension.js:5)
    at redux-devtools.extension.js:47
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Zone.runTask (zone-evergreen.js:168)
    at ZoneTask.invokeTask [as invoke] (zone-evergreen.js:465)
    at invokeTask (zone-evergreen.js:1603)
    at globalZoneAwareCallback (zone-evergreen.js:1629)
```

In my main.ts i have:
`ObservableStore.addExtension(new ReduxDevToolsExtension());`
The redux extension seems to be working fine in Chrome with the code there, but if i comment that code out, then the error disappears.

I'm currently using version 2.2.6 for both, but i was previously on version 2.2.3, which showed the same error.

**Comment by DanWahlin** [comment]
Thanks Trent. Can you let me know what version of Angular you're on? In running the samples included with the project I'm not able to duplicate that error (all of them are on v8 aside from one which is on v9) so I'm trying to figure out what scenario would cause it. Possibly an older version of Angular.

**Comment by trentsteel84** [comment]
Hi Dan,

This is from our package.json file
```json
"dependencies": {
        "@angular/animations": "~8.2.14",
        "@angular/common": "~8.2.14",
        "@angular/compiler": "~8.2.14",
        "@angular/core": "~8.2.14",
        "@angular/forms": "~8.2.14",
        "@angular/platform-browser": "~8.2.14",
        "@angular/platform-browser-dynamic": "~8.2.14",
        "@angular/router": "~8.2.14",
        "@codewithdan/observable-store": "^2.2.6",
        "@codewithdan/observable-store-extensions": "^2.2.6",
        "angular2-notifications": "^2.0.0",
        "core-js": "^2.5.4",
        "devextreme": "17.1.9",
        "devextreme-angular": "17.1.9",
        "font-awesome": "^4.7.0",
        "jquery": "^3.4.1",
        "leaflet": "^1.6.0",
        "leaflet.markercluster": "^1.4.1",
        "lodash": "^4.17.15",
        "ngx-auto-unsubscribe": "^3.0.1",
        "ngx-bootstrap": "^5.3.2",
        "ngx-cookie-service": "^2.2.0",
        "ngx-loading": "^8.0.0",
        "rxjs": "~6.5.3",
        "simple-line-icons": "^2.4.1",
        "subsink": "^1.0.0",
        "tslib": "^1.9.0",
        "zone.js": "~0.9.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "^0.803.22",
        "@angular/cli": "^8.3.19",
        "@angular/compiler-cli": "~8.2.14",
        "@angular/language-service": "~8.2.14",
        "@types/jasmine": "~2.8.8",
        "@types/jasminewd2": "~2.0.3",
        "@types/jquery": "^3.3.31",
        "@types/lodash": "^4.14.149",
        "@types/node": "^8.9.5",
        "codelyzer": "^5.0.1",
        "eslint": "^6.8.0",
        "jasmine-core": "~2.99.1",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.2.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.1",
        "karma-jasmine": "~1.1.2",
        "karma-jasmine-html-reporter": "^0.2.2",
        "protractor": "~5.4.0",
        "ts-node": "~7.0.0",
        "tslint": "~5.11.0",
        "typescript": "~3.5.3"
    }
```

**Comment by DanWahlin** [comment]
Thanks - I appreciate it. I'm baffled on this one since Angular 8 (and earlier versions) has the getAllAngularRootElements function. If you get a chance, can you try to run `samples/angular-store-edits` demo in this repo? It uses a similar version of Angular and works but I'm interested to see if you still get the same error. Here's how to run that (if you get time...no problem if you can't):

1. Clone the repo
2. npm install
3. ng serve -o

Do you have any browser extensions installed for Angular by chance? Also, you're not using any of the Angular 8 experimental stuff are you (Ivy for example)?

Something weird is definitely going on that I haven't run into so I'd love to get to the bottom of it. Thanks again.

**Comment by DanWahlin** [comment]
Actually - I think I found the problem although I wasn't able to duplicate the same error. I added initial support for Angular 9 and Ivy (it's not working yet since there's a missing API that they need to finish) and didn't realize that getAllAngularTestabilities was being called in v8. More details then you probably want, but it looks like the current version runs the correct v8 or less code but also runs the future v9 code which is incorrect.

After I run some more tests I'll let you know when a new version is pushed out. Thanks again for letting me know.

**Comment by DanWahlin** [comment]
I just pushed out 2.2.7 for both packages. I *think* it fixes the issue but since I wasn't able to duplicate that exact error you'll have to let me know.

**Comment by trentsteel84** [comment]
Hi Dan,
Sorry about the delay in getting back to you. No, we aren't using any V8 experimental stuff.
I tried the sample and didn't see the console error (that might be because you updated the package it's using though).
So i updated our code to 2.2.7 and now the console error has disappeared.
Thanks for all the help!
