### ISSUE TITLE
Question on sharing service

### ISSUE THREAD

**Issue by Godrules500** [DanWahlin/Observable-Store#57]
So I have a question and not an issue (I apologize if this is the wrong spot!), but I have a UserPermission service that extends ObservableStore.

My question is, if I am on a roles component, is there a way to hit the StateChanged without adding the customerService to the constructor of the roles service?

Also, is there a way to subscribe to only one of the state changed services instead of all of them? so something like userPermissionService.StateChanged.UserPermissions.subscribe(x={do fancy stuff here})?

Thanks in advance!

**Comment by DanWahlin** [comment]
I'm not clear on the first part of the question so let me walk through a scenario and see if that helps. Observable Store sends out change notifications made by a given service. So, if your UserPermission service changes something with setState(), any subscribers hooked to `userPermissionService.stateChanged` would get those changes. They wouldn't get changes made to the store through CustomersService unless they called `customersService.stateChanged` on it and subscribed. In sum, each service that extends Observable Service only sends out changes made by that particular service.

If you want to get changes made to the store by **any service** you can use the `myServiceName.globalStateChanged` option.

To know if a specific property changed such as userSettings, use the `stateWithPropertyChanges: Observable<StateWithPropertyChanges<T>>` option (https://github.com/danwahlin/observable-store#store-api). Here's an example:

```typescript
this.userPermissionsService.stateWithPropertyChanges.subscribe(stateWithProps => {
    if (stateWithProps && stateWithProps.stateChanges.userSettings) {
      // Do something since the target property did change
    }
});
```

Doing that works well when you only want to run some code when a specific property changes. 

As a heads-up, the latest version has a new function called `getStateProperty()` (see the link above for more details). Instead of retrieving (and cloning) the entire store, it'll let you pick a specific property from the store:

```typescript
// Somewhere in a service
this.getStateProperty<YourPropertyType>('userSettings');
```

**Comment by Godrules500** [comment]
Thanks Dan! Sorry for the confusion on the question, but you definitely answered all of the questions I had.

Thanks!
