### ISSUE TITLE
 stateChanged Observable<any>

### ISSUE THREAD

**Issue by mailok** [DanWahlin/Observable-Store#6]
Hi, you could make this Observable type T ?, it is so that it is more type safety

**Comment by DanWahlin** [comment]
Hi Mailok. Thanks for the suggestion. If the exact state defined with ObservableStore<T> was always returned we could do that, However, Observable Store also allows a `stateSliceSelector` function to be defined that allows custom state (a "slice" of the overall store for example) to be returned. So, we need to leave `any` to accommodate that feature...at least for now.

I could see a potential change to `public stateChanged: Observable<T | any>;` but I'd need to look into any ramifications of making that change on existing projects. Seems pretty safe on the surface, but would need to experiment more. Something I'll add to the list to research though as soon as I have some free time. Appreciate the suggestion.

**Comment by mailok** [comment]
@DanWahlin You are welcome.

**Comment by DanWahlin** [comment]
Thanks again for the suggestion. After thinking this through more I came to the conclusion that there's not a great way to change that while still supporting the new state slice feature (at least without introducing some new concepts). Since the state parameter returned from stateChanged can be typed, that solves the issue when no state slice function is defined and when one is defined so I'm going to leave that for now.

As enhancements are made in the future I'll keep this in mind though. Thanks!

**Comment by elAndyG** [comment]
@DanWahlin - I put together a small stackblitz to test out using `Partial<T>` as a possibility. I 'm able to get intellisense and it still updates only the properties a developer provides. I added a readme.md to point out some of the changes.  Would love to get your thoughts and submit a PR if it helps.

https://stackblitz.com/edit/observable-store-partial-r-and-d?file=foo.store.ts
