### ISSUE TITLE
Not able to save images in store state

### ISSUE THREAD

**Issue by SURBHU** [DanWahlin/Observable-Store#60]
Hi author, 
I was trying to store image file in the state. But, somehow its getting remove while storing. Please help me out with the solution.

**Comment by DanWahlin** [comment]
There wouldn't be a way to store an image file in any front-end state store unless you base64 encode the bytes. You could store a URL for an image as a property of the store of course, but that's entirely different.

Storing an actual image isn't something I'd recommend unless the image is really small because the store clones (ensures immutable data) store data and that could be expensive if the image is very big. If you really need to store an image on the front-end you might consider localStorage or sessionStorage. That way the image bytes/base64 data won't be cloned.

Since this isn't something I'd recommend for any front-end store I'm going to close the issue. But, if you still want to do it you'll need to convert the image to a byte[] and then base64 encode that for storage on anything related to the front-end.
