### ISSUE TITLE
Is it possible to subscribe to a single change?

### ISSUE THREAD

**Issue by gerardkd** [DanWahlin/Observable-Store#63]
Hi Dan,

First of all: thanks for this Observable Store! I come from a Vue / Vuex background and had some trouble fitting a NGRX / NGXS workflow in my mindset, but Observable Store 'clicked' inmediately.

I'm having trouble subscribing to a single change in Angular. I have the following structure in my (demo) store:

``` ts
{
  customer: Customer,
  customers: Customer[],
  sortBy: 'id'
}
```

I'm setting this initial state in the constructor, after calling `super`. I would like to be able to listen to the `sortBy` change in a component .ts file. In the template of this component, a user can click on table headers to change the sort. This is the code that is executed in the store:

``` ts
setSortBy(key: string): void {
  this.setState({ sortBy: key }, actions.changeSort);
}
```

I have a 'getter' for the current sort property in the store:

``` ts
getCurrentSort(): Observable<string> {
  return of(this.getState().sortBy);
}
```
If I use this method in my component HTML with a `async` pipe, it works great. But if I try to subscribe to it in the `.ts` file, I only see a change on init, not after change:

``` ts
this.customerStore.getCurrentSort().subscribe((sort) => {
  console.log('sorting change');
});
```

Is this intentional and is it **always** required to track changes in the component `.ts` via `stateChanged` and update all properties accordingly? It would be very convenient to be able to subscribe to single props in the state, but maybe I'm missing something or is this considered bad practice :).

**Comment by DanWahlin** [comment]
Hi Gerard. Longer walk-through answer first and I'll get to your question below. Any subscription to the observable returned from `getCurrentSort()` would receive data whenever `customerStore.getCurrentSort()` is called from somewhere in the app. That subscription doesn't have any association with Observable Store though (it just returns the `sortBy` value from it) since it's a custom function and a custom observable. If `sortBy` changes you wouldn't be notified by the store with that subscription since it's only triggered when `getCurrentSort()` is called by the app as mentioned. 

If you want to be notified as the `sortBy` value changes then you'd need to subscribe to `stateChanged` (returns all changes made by a given service that extends observable store), `stateWithPropertyChanges` (returns all changes along with what property changed),  `globalStateChanged`(returns all changes made to the store regardless of which service made it), or `globalStateWithPropertyChanges`. The documentation has more details and the samples show a few different ways to use `stateChanged`.

https://github.com/danwahlin/observable-store#store-api

So, to answer your question, yes, if you want to know when Observable Store changes you need to subscribe to one of the observables it provides such as `stateChanged`. To know if a specific property changed check out `stateWithPropertyChanges` since it'll give the state that changes as well as the specific property that changed.
