### ISSUE TITLE
setState slow with large array

### ISSUE THREAD

**Issue by Steve-RW** [DanWahlin/Observable-Store#64]
I have around 70000 objects in an array. I turn off deep cloning but setState is still a bit slow. Is it because deepCloneState isn't passed to getState() in the method?

Awesome library btw.

**Comment by DanWahlin** [comment]
Thanks Steve. If you're turning off deep cloning already (using the boolean parameter) when calling setState and when calling getState then there won't be much that can be done by the library since standard browser functionality/memory kicks in.

70,000 objects is definitely a lot of data so the only thing I can recommend is breaking it up into different properties (similar to the sharding concept in databases) so that when you're setting/getting values they're smaller.
