### ISSUE TITLE
Build warning for CommonJS with ng-cli 10

### ISSUE THREAD

**Issue by fergusg** [DanWahlin/Observable-Store#76]
Several dependencies (not just yours) give this message nowadays on `ng build --prod`

```
WARNING in [xxxxx]/store.ts depends on '@codewithdan/observable-store'. 
   CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

```
Angular CLI: 10.0.1
Node: 14.4.0
OS: darwin x64

Angular: 10.0.2
Ivy Workspace: Yes
```

```
"@codewithdan/observable-store": "^2.2.11",
```

**Comment by DanWahlin** [comment]
Thanks, I've noticed that as well with various scenarios. That's a new flag they added. 

It's due to how the module is loaded during the build. While I can change it (initially it used ES2015 modules which wouldn't give the warning), the current way modules are loaded with Observable Store is by design to accommodate issues submitted by people testing with jest who need commonJS . So, for the time being I'm going to leave it since making the change to get rid of the warning would break some people (and because Observable Store is so small it doesn't matter much either way).
