### ISSUE TITLE
Persisting data long term with expiry options

### ISSUE THREAD

**Issue by mrbilly222** [DanWahlin/Observable-Store#83]
The Observable Store needs to have the ability to persist data after closing the browser tab, window or navigating away from the web application.

This would need to be configurable both at the global level as well as an individual service level. Possible configurations would include how to store the data (i.e. local storage, cookies), assign a time to live, and a mechanism for invalidating data based on the time to live.

This feature could be will be very beneficial when setting and getting data that you expect to rarely or never change.

**Comment by DanWahlin** [comment]
Thanks for the suggestion. I've tossed that idea around in the past but decided against it since there are multiple ways to store state on the client-side (as you mention) and a dev can already do that on their own if they need it.

While it's not something I'm planning to add at this point since the overall goal is to keep the library super small with a minimal API, I'll add it to the list of future considerations for a potential add-on. Thanks again.
