### ISSUE TITLE
Incorrect result received in function subscribed to stateChanged

### ISSUE THREAD

**Issue by HEBOS** [DanWahlin/Observable-Store#90]
Hi Dan,

First of all, thank you for this great repository. I wanted to use it following your recommendation on Pluralsight.

However, there is a bug with what's being emitted through stateChanged observable.

In https://github.com/DanWahlin/Observable-Store/blob/master/modules/observable-store/observable-store.ts on line 20, we can see stateDispatcher being initialized with generic type T.

`private _stateDispatcher$ = new BehaviorSubject<T>(null);`

However on line 265, we can see that the state is incorrectly dispatched as a complex object, which has nothing to do with T.

`this._stateDispatcher$.next({ state: clonedStateOrSlice, stateChanges } as any);`

On line 61, we can see that stateChanged is in fact observable which emits, what stateDispatcher receives, expecting to forward T down the line.

`this.stateChanged = this._stateDispatcher$.asObservable();`

If we subscribe to stateChanged from our code, we get an incorrect object.

For example, instead of receiving:

`{ projects: Array<IProject>, project: IProject> }`

we get:
`{ state: { projects: Array<IProject>, project: IProject> }, stateChanges: ...}`

Strong typed result in subscribe function suggests that result.project should exist, however it is always null in runtime.
The only way to workaround that issue is to cast result to any, so I think this is a bug. 

If it was intention to emit the current state, and state changes, there should be a separate object for that.

For example:

```
export interface IStateChangedResult {
    state: T;
    stateChanges: T;
}

export class StateChangedResult implements IStateChangedResult {
    state: T;
    stateChanges: T;

    public constructor(init?: Partial<StateChangedResult>) {
        (<any>Object).assign(this, init);
    }
}
```

and then, on line 265 emit:
`this._stateDispatcher$.next(new StateChangedResult({ state: clonedStateOrSlice, stateChanges }));`

Of course, line 20, should then be replaced with:
`private _stateDispatcher$ = new BehaviorSubject<StateChangedResult<T>>(null);`

Any help is appreciated.
Thanks

**Comment by DanWahlin** [comment]
Hi @HEBOS. Thanks for the information.

If you're using `stateChanged` and getting **state** + **stateChanges** then the deprecated `includeStateChangesOnSubscribe` property must be set to true on the settings. There's no other way line 265 would be called. But, that is deprecated and shouldn't be hit unless you're using that specific settings property. 

In normal cases line 269 and 270 will be hit and getting **state** would be done using `stateChanged` whereas getting **state + stateChanges** would be done using `stateWithChanges`. We don't plan to change the type returned there since when requesting state + state changes with `stateWithChanges` you're explicitly asking for more. Plus, changing the type there would break existing clients which we can't do.

**Comment by HEBOS** [comment]
Thanks,

I had includeStateChangesOnSubscribe  in the super call. Once removed, everything works.
