### ISSUE TITLE
Is it necessary to deep clone the state when dispatching?

### ISSUE THREAD

**Issue by fifafu** [DanWahlin/Observable-Store#92]
I'm using this project with data that can not easily be deepCloned. I know deepCloning has a lot of advantages, but even without it, this library has been very helpful for me.

However with the current versions, it will always do a deep clone when using the setState function with dispatchState=true and deepCloneState = false. (because the dispatchState function doesn't care about any deepCloneState argument). Is this necessary for some reason?

If not I'd propose to make this optional, then I could continue to use this helpful library :-)

**Comment by DanWahlin** [comment]
The reason that's done is due to change detection in libraries/frameworks. In Angular for example, without cloning the dispatched object the object reference wouldn't change so the UI wouldn't know to update without manual coding. 

While the deepCloneState value could be passed into the dispatchState function, that could potentially break previous behavior  in existing apps using the library so I'm hesitant to change that functionality right now.

**Comment by fifafu** [comment]
Maybe adding a global setting which wouldn't break existing behavior and needs to be enabled manually?

I'm using it a bit like redux and create new object references before passing them to setState. So change detection seems to work fine even without deep cloning.

**Comment by DanWahlin** [comment]
I don't want to add any additional properties at this point (trying to keep the API as basic as possible....which is proving challenging to do over time :-)). While I don't have the bandwidth to implement the change right now to stop cloning during a dispatch right now (when deepCloneState is false), let me think it over more. I suspect it won't impact many (if any) people but I'm always careful there.

If you end up having time to submit a PR that modifies that behavior to fit what you need I'm happy to consider that as well and run it through some scenarios I have.

**Comment by fifafu** [comment]
Yep, I understand it's hard to keep things simple :-) 

I'll also think about this a bit more and submit my suggestion as a merge request (I'm already using a patched version of the lib for our app).

**Comment by DanWahlin** [comment]
That sounds great. I'll definitely give that more consideration because I kind of feel that if someone set deep cloning to false then the dispatch shouldn't need to deep clone given that they knew what they were doing when they set it to false.

If you're able to submit a PR for what you've modified for your scenario I'll look it over more. Thanks!

**Comment by DanWahlin** [comment]
Hi @fifafu. You're probably tied up with other things I know but if you get a chance to submit a PR with the changes you wanted let me know. Happy to look at it and see the impact on existing usage.

**Comment by DanWahlin** [comment]
Going to close this for now but feel free to re-open if you get a chance to submit the code you mentioned.
